name: cv
description: "Artur Saidov's Resume"
publish_to: "none"
version: 0.1.1+1

environment:
  sdk: ">=3.6.2 <4.0.0"
  flutter: ">=3.29.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
flutter_intl:
  enabled: true
